### ISSUE TITLE
Add option to show icon in app drawer

### ISSUE THREAD

**Issue by ghost** [kmark/XHangouts#1]
Hi, no way to have new line option, Google keyboard still on emojis button.
Take a look to the log below please.
Thanks.

13 déc. 2014 16:22:13 UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'cm_i9100-userdebug 4.4.4 KTU84Q 1d21e6e11d test-keys' with fingerprint 'samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys'
Loading modules from /data/app/com.vikas.toaststyler-1.apk
  Loading class com.vikas.toaststyler.XposedMod
Loading modules from /data/app/com.zst.xposed.xuimod-1.apk
  Loading class com.zst.xposed.xuimod.XuiMod
Loading modules from /data/app/com.pyler.enablecmcallrec-1.apk
  Loading class com.pyler.enablecmcallrec.EnableCallRecording
Loading modules from /data/app/com.versobit.kmark.xhangouts-1.apk
  Loading class com.versobit.kmark.xhangouts.XHangouts
Loading modules from /data/app/com.p1ngu1n.playstorechangelog-2.apk
  Loading class com.p1ngu1n.playstorechangelog.PlayStoreChangelog
Loading modules from /data/app/com.serajr.blurred.system.ui-1.apk
  Loading class com.serajr.blurred.system.ui.Xposed
Loading modules from /data/app/mjxl.xposed.indicators-2.apk
  Loading class mjxl.xposed.indicators.IndicatorsBeGone
Loading modules from /data/app/hk.kennethso168.xposed.apmplus-2.apk
  Loading class hk.kennethso168.xposed.apmplus.XMain
Loading modules from /data/app/me.jjohnson1988.android.xposed.removeactionoverflowbutton-1.apk
  Loading class me.jjohnson1988.android.xposed.removeactionoverflowbutton.OverflowHidden
Loading modules from /data/app/com.dhm47.nativeclipboard-2.apk
  Loading class com.dhm47.nativeclipboard.xposed.XposedMod
samsung
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
Loading modules from /data/app/de.galaxyinabox.xsuite2-1.apk
  Loading class de.galaxyinabox.xsuite2.XposedHooks.RenameHook
  Loading class de.galaxyinabox.xsuite2.XposedHooks.ReiconHook
  Loading class de.galaxyinabox.xsuite2.XposedHooks.AudioFocusHook
  Loading class de.galaxyinabox.xsuite2.XposedHooks.AppInfoHook
--- LOADING XHANGOUTS ---
XHangouts v1.5-20d8a19 (7)
Google Hangouts v2.5.81636427 (22147326)
XHangouts: Warning: Your Hangouts version differs from the version XHangouts was built against: v2.4.78234730 (22079529)
java.lang.NoSuchMethodError: bvx#a(int,int,int,int,android.net.Uri)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
    at com.versobit.kmark.xhangouts.XHangouts.handleLoadPackage(XHangouts.java:178)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
XHangouts: Context set.
--- LOADING XHANGOUTS ---
XHangouts v1.5-20d8a19 (7)
Google Hangouts v2.5.81636427 (22147326)
XHangouts: Warning: Your Hangouts version differs from the version XHangouts was built against: v2.4.78234730 (22079529)
java.lang.NoSuchMethodError: bvx#a(int,int,int,int,android.net.Uri)#exact
    at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:179)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:129)
    at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)
    at com.versobit.kmark.xhangouts.XHangouts.handleLoadPackage(XHangouts.java:178)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at android.app.ActivityThread.handleBindApplication(Native Method)
    at android.app.ActivityThread.access$1500(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5146)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
XHangouts: Context set.

**Comment by kmark** [comment]
You're running an unsupported version of Hangouts. Downgrade to the supported version specified in the logs or wait for me to update the module.

**Comment by ghost** [comment]
Ok thanks for your reply, so I'll wait the next update.
By the way, can you add an option for show icon in app drawer? 
Thanks.

**Comment by kmark** [comment]
I'll definitely look into it.

**Comment by kmark** [comment]
This will be available in the next release of XHangouts!

Ref: fe421f2e5d2e3208c8f05531f7622fffc7699f13

**Comment by ghost** [comment]
Thanks!

**Comment by kmark** [comment]
My pleasure. This feature is now available in v2.0.
