### ISSUE TITLE
Contact names almost impossible to read in dark theme

### ISSUE THREAD

**Issue by Fyren** [kmark/XHangouts#25]
Screenshot: https://photos.app.goo.gl/3fnlUgF6l7FGePC53

I built my own copy of XHangouts today from master and I'm using Hangouts 24.0.182154523.  With the dark theme turned on, it seems like the contrast between contact names and the background is way too low to read (at least for me; it's basically impossible on my device, but the screenshot isn't as bad viewed on my desktop).  It'd be great if the text color of the name was either changed by the theme or was customizable.

Let me know if there's any other info I can provide.

**Comment by ghost** [comment]
You'll see issues like that when you're using the wrong version of XHangouts or Hangouts. Check the log file in the Xposed installer and you might see errors.

I could upload an APK if it'd help? It would have a different signature, so you'd have to uninstall your own version.

**Comment by Fyren** [comment]
I'll try an APK if you want to build one, but I definitely built the latest revision from master and Hangouts is the version I mentioned according to Google Play.

**Comment by blackbox87** [comment]
https://github.com/blackbox87/XHangouts/releases/tag/v2.17

**Comment by blackbox87** [comment]
https://github.com/blackbox87/XHangouts/releases

**Comment by Fyren** [comment]
I tried XHangouts-34-v2.17-bb115de.apk from your repo, but the result is the same.

**Comment by ghost** [comment]
I'm using Nougat 7.1.0 and I've got Xposed framework version 89 installed. What are you using?

**Comment by Fyren** [comment]
My phone's pretty ancient.  I'm on 4.4.2 and Xposed framework 58.

I do see something in the Xposed logs:
<details>
<summary>
   de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.apps.hangouts.phone.BabelHomeActivity
</summary>
	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:52)

	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:136)

	at com.versobit.kmark.xhangouts.b.o.a(SourceFile:73)

	at com.versobit.kmark.xhangouts.XHangouts.handleLoadPackage(SourceFile:137)

	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)

	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)


	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)

	at de.robv.android.xposed.XposedBridge$1.beforeHookedMethod(XposedBridge.java:208)

	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)

	at android.app.ActivityThread.handleBindApplication(Native Method)

	at android.app.ActivityThread.access$1500(ActivityThread.java:139)

	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1260)

	at android.os.Handler.dispatchMessage(Handler.java:102)

	at android.os.Looper.loop(Looper.java:136)

	at android.app.ActivityThread.main(ActivityThread.java:5105)

	at java.lang.reflect.Method.invokeNative(Native Method)

	at java.lang.reflect.Method.invoke(Method.java:515)

	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)

	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)

	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

	at dalvik.system.NativeStart.main(Native Method)

   Caused by: java.lang.ClassNotFoundException: com.google.android.apps.hangouts.phone.BabelHomeActivity

	at java.lang.Class.classForName(Native Method)

	at java.lang.Class.forName(Class.java:251)

	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)

	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:50)

	... 20 more

   Caused by: java.lang.NoClassDefFoundError: com/google/android/apps/hangouts/phone/BabelHomeActivity

	... 24 more

   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.hangouts.phone.BabelHomeActivity" on path: DexPathList[[zip file "/system/framework/com.google.android.media.effects.jar", zip file "/data
/app/com.google.android.talk-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.google.android.talk-2, /vendor/lib, /system/lib]]

	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)

	... 24 more
</details>

**Comment by kmark** [comment]
A CNFException normally hints at a different Hangouts APK build. What's the version ID (not name) of your Hangouts?

**Comment by Fyren** [comment]
If you don't mean the version I gave in the initial post, I don't know what you mean.  Both Google Play and the app info from my apps list say 24.0.182154523.  XHangouts doesn't complain about my Hangouts version when I start it.

**Comment by kmark** [comment]
If you open XHangouts and go to the bottom it should tell you the version ID, in parenthesis I believe. It's a large integer.

**Comment by Fyren** [comment]
24746339.

**Comment by ghost** [comment]
It's weird because "com.google.android.apps.hangouts.phone.BabelHomeActivity" does exist and we only use it once in the UiVersionNotice class.

Open up XHangouts.java and comment out lines 137 and 168. If you compile that and still have issues then the error probably shifted to a different class.

**Comment by kmark** [comment]
I just did a quick search and it definitely exists in that version of Hangouts. That would make me think the issue is with the class loader..

**Comment by Fyren** [comment]
> Open up XHangouts.java and comment out lines 137 and 168. If you compile that and still have issues then the error probably shifted to a different class.

It does show a different class now, `dog`, from https://github.com/kmark/XHangouts/blob/master/app/src/main/java/com/versobit/kmark/xhangouts/mods/UiCallButtons.java#L83

**Comment by blackbox87** [comment]
Do you see a white splash screen when launching Hangouts? At this point I think you're either running into a compatibility issue or Xposed framework bug.

You could comment out all of the classes apart from UiColorize and then restore the others one at a time.

**Comment by ghost** [comment]
Do you see a white splash screen when launching Hangouts? At this point I think you're either running into a compatibility issue or an Xposed framework bug.

You could comment out all of the classes apart from UiColorize and then restore the others one at a time. Also make sure you do a full reboot instead of a soft reboot.

**Comment by Fyren** [comment]
> Do you see a white splash screen when launching Hangouts? At this point I think you're either running into a compatibility issue or Xposed framework bug.

The Hangouts splash screen does have a white background.

> You could comment out all of the classes apart from UiColorize and then restore the others one at a time.

I commented out just UiCallButtons (XHangouts.java:145) and the contact names are now white.  The splash screen still has a white background, should it not?

> Also make sure you do a full reboot instead of a soft reboot.

I have been.

**Comment by ghost** [comment]
>I commented out just UiCallButtons (XHangouts.java:145) and the contact names are now white. The splash screen still has a white background, should it not?

The splash screen should be white.

Do you still see various errors in the Xposed log? If you don't then you should alter the visibility of some of the buttons and check again. Maybe even try with the "show debug options" setting enabled.

**Comment by Fyren** [comment]
There aren't any errors in the Xposed log now.  I was able to hide the location button and re-enable it fine.  I turned on the debug settings option in XHangouts and I see the debug menu.

**Comment by ghost** [comment]
That's so strange! I guess I'll look into doing the version check a different way and try to catch the error in the other class.

I'll post again once I've made a few changes.

**Comment by blackbox87** [comment]
https://github.com/blackbox87/XHangouts/tree/testing

Compile my build and see if everything works. Just make sure you compile the testing branch.

You should only see an error logged within the UiCallButtons class if you've got debug mode enabled.

**Comment by Fyren** [comment]
Your branch works for me (names are white, adding/removing a button works, the Hangouts debug menu appears).  I do get the new log line you added if I turn on debug.
